

def get_feature_names():


    return {
        # Core Stats
        "PLAYER_NAME": "Player Name",
        "FGM": "Field Goals Made",
        "FGA": "Field Goals Attempted",
        "FG_PCT": "Field Goal %",
        "FG3M": "3PT Made",
        "FG3A": "3PT Attempted",
        "FG3_PCT": "3PT %",
        "FTM": "Free Throws Made",
        "FTA": "Free Throws Attempted",
        "FT_PCT": "Free Throw %",
        "OREB": "Offensive Rebounds",
        "DREB": "Defensive Rebounds",
        "REB": "Total Rebounds",
        "AST": "Assists",
        "TOV": "Turnovers",
        "STL": "Steals",
        "BLK": "Blocks",
        "BLKA": "Blocked Attempts",
        "PF": "Personal Fouls",
        "PFD": "Fouled Drawn",
        "PTS": "Points",
        "PLUS_MINUS": "Plus/Minus",
        "DD2": "Double-Doubles",
        "TD3": "Triple-Doubles",
        "W_PCT": "Win %",
        "NET_RATING": "Net Rating",
        "AST_PCT": "Assist %",
        "AST_TO": "Assist to Turnover Ratio",
        "AST_RATIO": "Assist Ratio",
        "OREB_PCT": "Offensive Rebound %",
        "DREB_PCT": "Defensive Rebound %",
        "REB_PCT": "Rebound %",
        "TM_TOV_PCT": "Team Turnover %",
        "EFG_PCT": "Effective FG %",
        "TS_PCT": "True Shooting %",
        "USG_PCT": "Usage %",
        "PIE": "Player Impact Estimate",
        "FGM_PG": "FG Made per Game",
        "FGA_PG": "FG Attempted per Game",
        "Season": "Season",

        # Transition Stats
        "Transition_FREQ": "Transition Frequency",
        "Transition_PPP": "Transition Points per Possession",
        "Transition_FG_PCT": "Transition FG %",
        "Transition_FT_POSS_PCT": "Transition FT per Possession %",
        "Transition_TOV_POSS_PCT": "Transition Turnover %",
        "Transition_SF_POSS_PCT": "Transition Shooting Foul %",
        "Transition_PLUSONE_POSS_PCT": "Transition +1 Possession %",
        "Transition_SCORE_POSS_PCT": "Transition Scoring Possession %",
        "Transition_EFG_PCT": "Transition Effective FG %",
        "Transition_POSS": "Transition Possessions",
        "Transition_PTS": "Transition Points",
        "Transition_FGM": "Transition FG Made",
        "Transition_FGA": "Transition FG Attempted",
        "Transition_FGMX": "Transition FG Made Extra?",

        # Isolation Stats
        "Isolation_FREQ": "Isolation Frequency",
        "Isolation_PPP": "Isolation Points per Possession",
        "Isolation_FG_PCT": "Isolation FG %",
        "Isolation_FT_POSS_PCT": "Isolation FT per Possession %",
        "Isolation_TOV_POSS_PCT": "Isolation Turnover %",
        "Isolation_SF_POSS_PCT": "Isolation Shooting Foul %",
        "Isolation_PLUSONE_POSS_PCT": "Isolation +1 Possession %",
        "Isolation_SCORE_POSS_PCT": "Isolation Scoring Possession %",
        "Isolation_EFG_PCT": "Isolation Effective FG %",
        "Isolation_POSS": "Isolation Possessions",
        "Isolation_PTS": "Isolation Points",
        "Isolation_FGM": "Isolation FG Made",
        "Isolation_FGA": "Isolation FG Attempted",
        "Isolation_FGMX": "Isolation FG Made Extra?",

        # Pick & Roll Ball Handler
        "PRBallHandler_FREQ": "Pick&Roll BH Frequency",
        "PRBallHandler_PPP": "Pick&Roll BH Points per Possession",
        "PRBallHandler_FG_PCT": "Pick&Roll BH FG %",
        "PRBallHandler_FT_POSS_PCT": "Pick&Roll BH FT per Possession %",
        "PRBallHandler_TOV_POSS_PCT": "Pick&Roll BH Turnover %",
        "PRBallHandler_SF_POSS_PCT": "Pick&Roll BH Shooting Foul %",
        "PRBallHandler_PLUSONE_POSS_PCT": "Pick&Roll BH +1 Possession %",
        "PRBallHandler_SCORE_POSS_PCT": "Pick&Roll BH Scoring Possession %",
        "PRBallHandler_EFG_PCT": "Pick&Roll BH Effective FG %",
        "PRBallHandler_POSS": "Pick&Roll BH Possessions",
        "PRBallHandler_PTS": "Pick&Roll BH Points",
        "PRBallHandler_FGM": "Pick&Roll BH FG Made",
        "PRBallHandler_FGA": "Pick&Roll BH FG Attempted",
        "PRBallHandler_FGMX": "Pick&Roll BH FG Made Extra?",

        # Pick & Roll Rollman
        "PRRollman_FREQ": "Pick&Roll RM Frequency",
        "PRRollman_PPP": "Pick&Roll RM Points per Possession",
        "PRRollman_FG_PCT": "Pick&Roll RM FG %",
        "PRRollman_FT_POSS_PCT": "Pick&Roll RM FT per Possession %",
        "PRRollman_TOV_POSS_PCT": "Pick&Roll RM Turnover %",
        "PRRollman_SF_POSS_PCT": "Pick&Roll RM Shooting Foul %",
        "PRRollman_PLUSONE_POSS_PCT": "Pick&Roll RM +1 Possession %",
        "PRRollman_SCORE_POSS_PCT": "Pick&Roll RM Scoring Possession %",
        "PRRollman_EFG_PCT": "Pick&Roll RM Effective FG %",
        "PRRollman_POSS": "Pick&Roll RM Possessions",
        "PRRollman_PTS": "Pick&Roll RM Points",
        "PRRollman_FGM": "Pick&Roll RM FG Made",
        "PRRollman_FGA": "Pick&Roll RM FG Attempted",
        "PRRollman_FGMX": "Pick&Roll RM FG Made Extra?",

        # Postup
        "Postup_FREQ": "Postup Frequency",
        "Postup_PPP": "Postup Points per Possession",
        "Postup_FG_PCT": "Postup FG %",
        "Postup_FT_POSS_PCT": "Postup FT per Possession %",
        "Postup_TOV_POSS_PCT": "Postup Turnover %",
        "Postup_SF_POSS_PCT": "Postup Shooting Foul %",
        "Postup_PLUSONE_POSS_PCT": "Postup +1 Possession %",
        "Postup_SCORE_POSS_PCT": "Postup Scoring Possession %",
        "Postup_EFG_PCT": "Postup Effective FG %",
        "Postup_POSS": "Postup Possessions",
        "Postup_PTS": "Postup Points",
        "Postup_FGM": "Postup FG Made",
        "Postup_FGA": "Postup FG Attempted",
        "Postup_FGMX": "Postup FG Made Extra?",

        # Spotup
        "Spotup_FREQ": "Spotup Frequency",
        "Spotup_PPP": "Spotup Points per Possession",
        "Spotup_FG_PCT": "Spotup FG %",
        "Spotup_FT_POSS_PCT": "Spotup FT per Possession %",
        "Spotup_TOV_POSS_PCT": "Spotup Turnover %",
        "Spotup_SF_POSS_PCT": "Spotup Shooting Foul %",
        "Spotup_PLUSONE_POSS_PCT": "Spotup +1 Possession %",
        "Spotup_SCORE_POSS_PCT": "Spotup Scoring Possession %",
        "Spotup_EFG_PCT": "Spotup Effective FG %",
        "Spotup_POSS": "Spotup Possessions",
        "Spotup_PTS": "Spotup Points",
        "Spotup_FGM": "Spotup FG Made",
        "Spotup_FGA": "Spotup FG Attempted",
        "Spotup_FGMX": "Spotup FG Made Extra?",

        # Handoff
        "Handoff_FREQ": "Handoff Frequency",
        "Handoff_PPP": "Handoff Points per Possession",
        "Handoff_FG_PCT": "Handoff FG %",
        "Handoff_FT_POSS_PCT": "Handoff FT per Possession %",
        "Handoff_TOV_POSS_PCT": "Handoff Turnover %",
        "Handoff_SF_POSS_PCT": "Handoff Shooting Foul %",
        "Handoff_PLUSONE_POSS_PCT": "Handoff +1 Possession %",
        "Handoff_SCORE_POSS_PCT": "Handoff Scoring Possession %",
        "Handoff_EFG_PCT": "Handoff Effective FG %",
        "Handoff_POSS": "Handoff Possessions",
        "Handoff_PTS": "Handoff Points",
        "Handoff_FGM": "Handoff FG Made",
        "Handoff_FGA": "Handoff FG Attempted",
        "Handoff_FGMX": "Handoff FG Made Extra?",

        # Cut
        "Cut_FREQ": "Cut Frequency",
        "Cut_PPP": "Cut Points per Possession",
        "Cut_FG_PCT": "Cut FG %",
        "Cut_FT_POSS_PCT": "Cut FT per Possession %",
        "Cut_TOV_POSS_PCT": "Cut Turnover %",
        "Cut_SF_POSS_PCT": "Cut Shooting Foul %",
        "Cut_PLUSONE_POSS_PCT": "Cut +1 Possession %",
        "Cut_SCORE_POSS_PCT": "Cut Scoring Possession %",
        "Cut_EFG_PCT": "Cut Effective FG %",
        "Cut_POSS": "Cut Possessions",
        "Cut_PTS": "Cut Points",
        "Cut_FGM": "Cut FG Made",
        "Cut_FGA": "Cut FG Attempted",
        "Cut_FGMX": "Cut FG Made Extra?",

        # OffScreen
        "OffScreen_FREQ": "OffScreen Frequency",
        "OffScreen_PPP": "OffScreen Points per Possession",
        "OffScreen_FG_PCT": "OffScreen FG %",
        "OffScreen_FT_POSS_PCT": "OffScreen FT per Possession %",
        "OffScreen_TOV_POSS_PCT": "OffScreen Turnover %",
        "OffScreen_SF_POSS_PCT": "OffScreen Shooting Foul %",
        "OffScreen_PLUSONE_POSS_PCT": "OffScreen +1 Possession %",
        "OffScreen_SCORE_POSS_PCT": "OffScreen Scoring Possession %",
        "OffScreen_EFG_PCT": "OffScreen Effective FG %",
        "OffScreen_POSS": "OffScreen Possessions",
        "OffScreen_PTS": "OffScreen Points",
        "OffScreen_FGM": "OffScreen FG Made",
        "OffScreen_FGA": "OffScreen FG Attempted",
        "OffScreen_FGMX": "OffScreen FG Made Extra?",

        # OffRebound
        "OffRebound_FREQ": "Offensive Rebound Frequency",
        "OffRebound_PPP": "OffRebound Points per Possession",
        "OffRebound_FG_PCT": "OffRebound FG %",
        "OffRebound_FT_POSS_PCT": "OffRebound FT per Possession %",
        "OffRebound_TOV_POSS_PCT": "OffRebound Turnover %",
        "OffRebound_SF_POSS_PCT": "OffRebound Shooting Foul %",
        "OffRebound_PLUSONE_POSS_PCT": "OffRebound +1 Possession %",
        "OffRebound_SCORE_POSS_PCT": "OffRebound Scoring Possession %",
        "OffRebound_EFG_PCT": "OffRebound Effective FG %",
        "OffRebound_POSS": "OffRebound Possessions",
        "OffRebound_PTS": "OffRebound Points",
        "OffRebound_FGM": "OffRebound FG Made",
        "OffRebound_FGA": "OffRebound FG Attempted",
        "OffRebound_FGMX": "OffRebound FG Made Extra?",

        # Misc
        "Misc_FREQ": "Misc Frequency",
        "Misc_PPP": "Misc Points per Possession",
        "Misc_FG_PCT": "Misc FG %",
        "Misc_FT_POSS_PCT": "Misc FT per Possession %",
        "Misc_TOV_POSS_PCT": "Misc Turnover %",
        "Misc_SF_POSS_PCT": "Misc Shooting Foul %",
        "Misc_PLUSONE_POSS_PCT": "Misc +1 Possession %",
        "Misc_SCORE_POSS_PCT": "Misc Scoring Possession %",
        "Misc_EFG_PCT": "Misc Effective FG %",
        "Misc_POSS": "Misc Possessions",
        "Misc_PTS": "Misc Points",
        "Misc_FGM": "Misc FG Made",
        "Misc_FGA": "Misc FG Attempted",
        "Misc_FGMX": "Misc FG Made Extra?",

        # 3 Pointers
        "3 Pointers_FREQ": "3PT Frequency",
        "3 Pointers_FG3M": "3PT Made",
        "3 Pointers_FG3A": "3PT Attempted",
        "3 Pointers_FG3_PCT": "3PT %",
        "3 Pointers_NS_FG3_PCT": "Non-Shoot 3PT %",
        "3 Pointers_PLUSMINUS": "3PT Plus/Minus",

        # 2 Pointers
        "2 Pointers_FREQ": "2PT Frequency",
        "2 Pointers_FG2M": "2PT Made",
        "2 Pointers_FG2A": "2PT Attempted",
        "2 Pointers_FG2_PCT": "2PT %",
        "2 Pointers_NS_FG2_PCT": "Non-Shoot 2PT %",
        "2 Pointers_PLUSMINUS": "2PT Plus/Minus",

        # Less Than 6Ft
        "Less Than 6Ft_FREQ": "<6Ft Frequency",
        "Less Than 6Ft_FGM_LT_06": "<6Ft FG Made",
        "Less Than 6Ft_FGA_LT_06": "<6Ft FG Attempted",
        "Less Than 6Ft_LT_06_PCT": "<6Ft FG %",
        "Less Than 6Ft_NS_LT_06_PCT": "<6Ft Non-Shoot %",
        "Less Than 6Ft_PLUSMINUS": "<6Ft Plus/Minus",

        # Less Than 10Ft
        "Less Than 10Ft_FREQ": "<10Ft Frequency",
        "Less Than 10Ft_FGM_LT_10": "<10Ft FG Made",
        "Less Than 10Ft_FGA_LT_10": "<10Ft FG Attempted",
        "Less Than 10Ft_LT_10_PCT": "<10Ft FG %",
        "Less Than 10Ft_NS_LT_10_PCT": "<10Ft Non-Shoot %",
        "Less Than 10Ft_PLUSMINUS": "<10Ft Plus/Minus",

        # Greater Than 15Ft
        "Greater Than 15Ft_FREQ": ">15Ft Frequency",
        "Greater Than 15Ft_FGM_GT_15": ">15Ft FG Made",
        "Greater Than 15Ft_FGA_GT_15": ">15Ft FG Attempted",
        "Greater Than 15Ft_GT_15_PCT": ">15Ft FG %",
        "Greater Than 15Ft_NS_GT_15_PCT": ">15Ft Non-Shoot %",
        "Greater Than 15Ft_PLUSMINUS": ">15Ft Plus/Minus"
    }
